#!/bin/sh

# Runs the FA archiver for the storage ring.  This runs on fa-archiver server.

ARCHIVE_FILE=/dev/sr_archive
ARCHIVE_NAME=SR
SNIFFER_DEV=/dev/fa_sniffer0
FA_ID_LIST=/home/ops/diagnostics/config/fa-ids.sr
EXTRA_ARGS=(-E255)

source "$(dirname "$0")"/run_archiver
