#!/bin/sh

# These definitions are designed to be overridden by the installer.
PYTHON=python
HERE="$(dirname "$(readlink -f "$0")")"

# Nasty hack to work around ESRF configuration problem
unset LD_LIBRARY_PATH

# Ensure that falib is on the python path
export PYTHONPATH="$HERE${PYTHONPATH:+:}$PYTHONPATH"
exec "$PYTHON" "$HERE"/viewer/fa_viewer.py "$@"
